### ISSUE TITLE
1Password7 exports fail to import

### ISSUE THREAD

**Issue by sectary-want-holly** [juanii/OnePIF#3] opened 2019-01-10 02:08 UTC
Exporting from latest MacOS 1password7 release, upon attempting to import into KeePass 2.40 a pop up appears stating:

"Guid should contain 32 digits with 4 dashes"

Regardless of vault exported, the same message persists upon attempting import.

**Comment by sectary-want-holly** [comment] 2019-01-10 02:19
OK - I see what's happened, and it's my fault. 1Password7 exports are not supported. The fix is to:

export from 1Password7;
import to 1Password4; 
export from 1Password4; 
import to KeePass2

Any chance of 1Password7 1pif support? :)

**Comment by juanii** [comment] 2019-01-10 14:29
Hi! Thank you very much for your bug report!

Yes, I definitely want to add 1Password 7 support, but unfortunately I don't own a license for that version to create a sample vault and take a look at the exported 1pif file. To be honest I didn't even downloaded it to see if it has a trial mode capable of loading my sample OPVault and exporting it to 1pif. Also I didn't consider signing up for a trial membership. ~Maybe I'll try the first option and, if it works, I might be able to add support for this (new?) 1pif file format.~
Edit: I just tried it loading my sample OPVault in 1P7 and exporting to 1pif, but the resulting file has the IDs unchanged (this is a behavior I've seen before) so my only chance is to sign up for a trial subscription or get your help with some sample items _created_ in 1P7.

In the meantime, if you have some anonymized/redacted sample you can upload here or anywhere else, I can take a look at it and see if it's just a simple matter. From your report, the parsing of the item ID is failing due to improper formatting.

Regards

**Comment by sectary-want-holly** [comment] 2019-01-10 15:32
> get your help with some sample items created in 1P7.

I can do this.  I'll create a new Vault in 1Password7 and create an entry for each category ready for export to 1PIF.

Would that be all you need?

Thanks!

**Comment by juanii** [comment] 2019-01-10 15:46
Yes that would be all. I usually create one item of each kind and fill all the template fields with dummy data. You can then export it as 1pif. The icing on the cake would be to enable Dropbox sync for that vault, then go to the Dropbox folder and backup the *.opvalut bundle (folder). This makes a good source to import into other 1Password versions.

If you want to make sure the 1pif file you generate is in the same format as the file that failed in the first place, please open the data.1pif file created by 1Password with a text editor (TextEdit is more than enough) and search for the "uuid" string (with the quotes) and check its value does **not** look like this one:

`"uuid":"0D46D01FA1C3455090449EC5354E7981"`

What I mean is it should be different from a 32-character string composed of numbers and A-through-F.

Anyway, I think just the 1pif file is more than enough to solve the problem, the other requests are just to have a broader set of samples.

Thank you very much for your help.

Regards

**Comment by sectary-want-holly** [comment] 2019-01-11 03:34
Hi @juanii 

[updated $subject for accuracy]

Thank you again for looking at this so promptly.  Sorry for the delay - long day at work. 

I've created a new vault with dummy data in 1Password7 and exported it here: https://github.com/sectary-want-holly/uploads/blob/master/data.1pif 

The UUID is in line with what you expected to see: "uuid":"apmtrm7t45h2xo7jjiuw5xruce" 

> The icing on the cake would be to enable Dropbox sync for that vault, then go to the Dropbox folder 
> and backup the *.opvalut bundle (folder). This makes a good source to import into other 1Password 
> versions.

Done. 
https://github.com/sectary-want-holly/uploads/tree/master/Example.opvault 
password: password123!

**Comment by juanii** [comment] 2019-01-11 03:46
That was quick. Thank you very much for your prompt help, with the icing and everything :) I'll take a look at this ASAP (probably tomorrow). Hoping it's just the IDs, since the fix would be very easy.

Regards.

**Comment by juanii** [comment] 2019-01-11 13:05
I've ben looking at this for a while. I suspect the IDs are just the normal UUIDs but Base32 encoded (26 characters long, the alphabet is a-through-z and 2-through-9) but I don't think it's RFC 4648 Base32 nor z-base-32. Or at least I still couldn't find a way to get the hexstring from the corresponding Base32 string.

Anyway since folders were removed from 1P7, the only other use for an item's UUID is to link to its attachments. If the attachments folder is named using the Base32 string I can get away with it. I don't care what the ID looks like as long as it is consistently used everywhere. But if the normal hexstring is used for the attachments folders, I'd need to find the decoding algorithm.

So if I could make one last request, can you please add an attachment to any of the items (just a simple file containing a single character is enough) and export to 1pif again? The exported root folder should contain an `attachments` folder and, inside it, another folder with an ID as its name. That ID is what I'm interested in. I'm referring to the `8B31F55D697941DDA65F78DD03F917EB` string in [this example](https://github.com/juanii/OnePIF/tree/master/Sample%20vaults/1P6-macOS.1pif).

Thanks again for your time and collaboration!

Edit: BTW, I found another person with a standalone version of 1P7. He imported your vault, added the file and exported the 1pif file, but the IDs are in hexstring (_normal_) format. May I ask if you're using 1Password standalone or with a 1Password.com subscription? Is it the latest 7.2.4 version? Do you do something special to export or just the normal `File > Export > All Items...`? I'm struggling to reproduce your exports but to no avail.

**Comment by sectary-want-holly** [comment] 2019-01-11 16:03
Hi @juanii 

Thanks for the quick help.

> So if I could make one last request, can you please add an attachment to any of the items (just a simple file containing a single character is enough) and export to 1pif again? 

Definitely. I need my MacBook to perform the export to 1pif, so I'll do this once home. 

> Edit: BTW, I found another person with a standalone version of 1P7. He imported your vault, added the file and exported the 1pif file, but the IDs are in hexstring (normal) format. 

Interesting. I wonder which version they were using? My details are below.

> May I ask if you're using 1Password standalone or with a 1Password.com subscription?

Subscription. 

> Is it the latest 7.2.4 version?

7.2.4 on MacOS. 

> Do you do something special to export or just the normal File > Export > All Items...?

I'm not in front of my Mac now, but from memory, yes, exactly that. I then select export as 1PIF.

**Comment by juanii** [comment] 2019-01-11 18:40
> Interesting. I wonder which version they were using? My details are below.

I think he used the latest 1P7 version, for sure it was no older than 7.2. Given there are no other differences my suspicion is that the subscription is the key, and the roundtrip to the 1Password.com server might be changing the ID. It's not uncommon to use Base32 encoded UUIDs as URL-friendly IDs. What's not so common is using a seemingly non-standard encoding :)

Once the attachments thing is sorted out, I think I'd be ready to release a new version with initial support for 1P7. There's still more work to do for _full_ support (e.g. I think there's a new Document item type for subscription users). I didn't want to, but after all I might end up signing for the trial so I can test without bothering others. I hope at last you can benefit from all this!

Regards.

**Comment by sectary-want-holly** [comment] 2019-01-11 20:19
Thank you! 

Let me get the attachment update to you later tonight (UTC -5).

**Comment by sectary-want-holly** [comment] 2019-01-12 00:07
Hi @juanii 

So, interestingly, when syncing a local vault, there is the option to add attachments to entries. 

However, this ability does _not_ exist when using a 1Password subscription vault. Instead, one has to add a 'Document'. When exporting this (subscription) Vault, a message is generated stating attachments can't be exported. 

I've made a local export available here with a couple of attachments added.
https://github.com/sectary-want-holly/uploads/tree/master/1Password%202019-01-11.1pif 
password: password123!

I hope that helps?

**Comment by sectary-want-holly** [comment] 2019-01-12 02:04
Just a quick update. I've managed to export from 1Password7 into Keepass2 successfully, retaining all custom fields.  

The workaround is to copy the items from your 1Password Cloud Vault to a local Vault. From this local vault, export to 1pif. This creates a 1pif which can be imported successfully into KeePass2.

I strongly suspect this is how the other person generated a 1pif in hexstring format. 

We're getting closer... :)

**Comment by juanii** [comment] 2019-01-12 03:55
Interesting indeed. And very odd you can't export your own documents from the online service… This thread was very instructive for me on how the cloud service works, thank you very much for your help.

Since it does no harm, I will release a new version supporting the IDs from the cloud vault so this glitch doesn't catch anyone else and close the issue. Given there won't ever be attachment files exported along those vaults, the attachments import can't possibly fail. Feel free to reopen the issue or open another one if you find something's missing.

I'll keep reading and researching how the cloud and local vaults interact to better understand if there's something that might be left behind in the import process. In the meantime, I'll add a paragraph to the README advising to copy the cloud vault to a local one before exporting.

Thanks again and enjoy the new version, with a couple of new features and bug fixes. BTW, can I add your sample vault to my repository?

Regards.

**Closed as completed** 2019-01-12 03:56 UTC
Labels: enhancement

**Comment by sectary-want-holly** [comment] 2019-01-12 04:01
> I will release a new version supporting the IDs from the cloud vault so this glitch doesn't catch anyone else and close the issue.

Thank you! This is really great of you. 

> BTW, can I add your sample vault to my repository?

Absolutely! 

I can confirm 0.4.0 resolves the issue! Superstar!
